// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

// 定义包名

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 定义 Req 消息结构
type AgentReq struct {
	// 类型 字段 = 标识号
	ReqType              string   `protobuf:"bytes,1,opt,name=reqType,proto3" json:"reqType,omitempty"`
	ReqToken             string   `protobuf:"bytes,2,opt,name=reqToken,proto3" json:"reqToken,omitempty"`
	ReqContent           []byte   `protobuf:"bytes,3,opt,name=reqContent,proto3" json:"reqContent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentReq) Reset()         { *m = AgentReq{} }
func (m *AgentReq) String() string { return proto.CompactTextString(m) }
func (*AgentReq) ProtoMessage()    {}
func (*AgentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *AgentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentReq.Unmarshal(m, b)
}
func (m *AgentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentReq.Marshal(b, m, deterministic)
}
func (m *AgentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentReq.Merge(m, src)
}
func (m *AgentReq) XXX_Size() int {
	return xxx_messageInfo_AgentReq.Size(m)
}
func (m *AgentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentReq.DiscardUnknown(m)
}

var xxx_messageInfo_AgentReq proto.InternalMessageInfo

func (m *AgentReq) GetReqType() string {
	if m != nil {
		return m.ReqType
	}
	return ""
}

func (m *AgentReq) GetReqToken() string {
	if m != nil {
		return m.ReqToken
	}
	return ""
}

func (m *AgentReq) GetReqContent() []byte {
	if m != nil {
		return m.ReqContent
	}
	return nil
}

// 定义 Res 消息结构
type AgentRes struct {
	ResType              string   `protobuf:"bytes,1,opt,name=resType,proto3" json:"resType,omitempty"`
	ReqToken             string   `protobuf:"bytes,2,opt,name=reqToken,proto3" json:"reqToken,omitempty"`
	ResContent           []byte   `protobuf:"bytes,3,opt,name=resContent,proto3" json:"resContent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentRes) Reset()         { *m = AgentRes{} }
func (m *AgentRes) String() string { return proto.CompactTextString(m) }
func (*AgentRes) ProtoMessage()    {}
func (*AgentRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *AgentRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentRes.Unmarshal(m, b)
}
func (m *AgentRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentRes.Marshal(b, m, deterministic)
}
func (m *AgentRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentRes.Merge(m, src)
}
func (m *AgentRes) XXX_Size() int {
	return xxx_messageInfo_AgentRes.Size(m)
}
func (m *AgentRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentRes.DiscardUnknown(m)
}

var xxx_messageInfo_AgentRes proto.InternalMessageInfo

func (m *AgentRes) GetResType() string {
	if m != nil {
		return m.ResType
	}
	return ""
}

func (m *AgentRes) GetReqToken() string {
	if m != nil {
		return m.ReqToken
	}
	return ""
}

func (m *AgentRes) GetResContent() []byte {
	if m != nil {
		return m.ResContent
	}
	return nil
}

func init() {
	proto.RegisterType((*AgentReq)(nil), "proto.AgentReq")
	proto.RegisterType((*AgentRes)(nil), "proto.AgentRes")
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77) }

var fileDescriptor_56ede974c0020f77 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4c, 0x4f, 0xcd,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x09, 0x5c, 0x1c, 0x8e,
	0x20, 0xd1, 0xa0, 0xd4, 0x42, 0x21, 0x09, 0x2e, 0xf6, 0xa2, 0xd4, 0xc2, 0x90, 0xca, 0x82, 0x54,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0x48, 0x8a, 0x8b, 0x03, 0xc4, 0xcc, 0xcf,
	0x4e, 0xcd, 0x93, 0x60, 0x02, 0x4b, 0xc1, 0xf9, 0x42, 0x72, 0x5c, 0x5c, 0x45, 0xa9, 0x85, 0xce,
	0xf9, 0x79, 0x25, 0xa9, 0x79, 0x25, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x48, 0x22, 0x48,
	0x36, 0x14, 0x43, 0x6c, 0x28, 0x46, 0xb5, 0xa1, 0x98, 0x38, 0x1b, 0x8a, 0x31, 0x6c, 0x80, 0x89,
	0x24, 0xb1, 0x81, 0xbd, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x23, 0xa4, 0x4b, 0x0b, 0xe0,
	0x00, 0x00, 0x00,
}
